# Generated by Django 2.1.2 on 2018-10-22 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models
import objdetec.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', objdetec.fields.SingleLineTextField(unique=True, verbose_name='Name')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('image', models.ImageField(max_length=4096, upload_to=images.models.get_image_path, verbose_name='Image')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.Set', verbose_name='Set')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('name',),
            },
        ),
    ]
