# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of objdetec.
#
# objdetec is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# objdetec is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with objdetec.  If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 2.0.4 on 2018-05-02 06:52

from django.db import migrations, models
import django.db.models.deletion
import nnmodels.models
import objdetec.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nnmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', objdetec.fields.SingleLineTextField(verbose_name='Name')),
                ('model_file', models.FileField(max_length=4096, upload_to=nnmodels.models.get_file_path, verbose_name='Model file')),
                ('trainhistory_file', models.FileField(blank=True, max_length=4096, null=True, upload_to=nnmodels.models.get_file_path, verbose_name='Train-history file')),
                ('nnmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='nnmodels.NNModel', verbose_name='NN Model')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('nnmodel', '-updated_at'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('nnmodel', 'name')},
        ),
    ]
