# Generated by Django 2.1.2 on 2018-10-24 18:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import nnmodels.models
import objdetec.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nnmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', objdetec.fields.SingleLineTextField(verbose_name='Name')),
                ('model_file', models.FileField(max_length=4096, upload_to=nnmodels.models.get_file_path, verbose_name='Model file')),
                ('trainhistory_file', models.FileField(blank=True, max_length=4096, null=True, upload_to=nnmodels.models.get_file_path, verbose_name='Train-history file')),
                ('state', django_fsm.FSMField(default='new', max_length=50, verbose_name='State')),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=objdetec.fields.SingleLineTextField(), blank=True, null=True, size=None, verbose_name='Inputs')),
                ('outputs', django.contrib.postgres.fields.ArrayField(base_field=objdetec.fields.SingleLineTextField(), blank=True, null=True, size=None, verbose_name='Outputs')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config')),
                ('nb_trainable', models.PositiveIntegerField(blank=True, null=True, verbose_name='Trainable params')),
                ('nb_non_trainable', models.PositiveIntegerField(blank=True, null=True, verbose_name='Non-trainable params')),
                ('nnmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='nnmodels.NNModel', verbose_name='NN Model')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('nnmodel', '-updated_at'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('nnmodel', 'name')},
        ),
    ]
