# Generated by Django 2.0.5 on 2018-06-07 09:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm
import objdetec.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nnmodels', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config'),
        ),
        migrations.AddField(
            model_name='version',
            name='inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=objdetec.fields.SingleLineTextField(), blank=True, null=True, size=None, verbose_name='Inputs'),
        ),
        migrations.AddField(
            model_name='version',
            name='nb_non_trainable',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Non-trainable params'),
        ),
        migrations.AddField(
            model_name='version',
            name='nb_trainable',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Trainable params'),
        ),
        migrations.AddField(
            model_name='version',
            name='outputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=objdetec.fields.SingleLineTextField(), blank=True, null=True, size=None, verbose_name='Outputs'),
        ),
        migrations.AddField(
            model_name='version',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, verbose_name='State'),
        ),
    ]
